# Generated by Django 5.0.1 on 2024-01-03 08:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=15)),
                ('avatar', models.ImageField(upload_to='images', verbose_name='avatar')),
                ('about', models.TextField()),
                ('wikimedia', models.URLField()),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Compositors',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('music', models.FileField(upload_to='musics', verbose_name='Wideo')),
                ('music_image', models.ImageField(upload_to='video_images', verbose_name='Image of video')),
                ('view', models.IntegerField(default=0)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('uploaded_time', models.DateField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classic_music_app.compositor')),
            ],
        ),
    ]
