# Generated by Django 5.0.1 on 2024-01-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classic_music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compositor',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='compositor',
            name='surname',
        ),
    ]
