# Generated by Django 5.0.1 on 2024-01-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_music_app', '0002_rename_firstname_compositor_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositor',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
