# Generated by Django 5.0.1 on 2024-01-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_music_app', '0003_alter_compositor_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositor',
            name='song_count',
            field=models.IntegerField(default=0),
        ),
    ]
