# Generated by Django 5.0.1 on 2024-01-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_music_app', '0004_compositor_song_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_image',
            field=models.ImageField(blank=True, upload_to='video_images', verbose_name='Image of video'),
        ),
    ]
