# Generated by Django 5.0.1 on 2024-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_music_app', '0005_alter_music_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositor',
            name='registered_time',
            field=models.DateField(auto_now=True),
        ),
    ]
