# Generated by Django 5.0.1 on 2024-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_music_app', '0006_compositor_registered_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='melody',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
