# Generated by Django 3.2 on 2024-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classic_music_app', '0009_alter_music_melody'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositor',
            name='views',
        ),
        migrations.RemoveField(
            model_name='music',
            name='view',
        ),
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(upload_to='musics', verbose_name='Saz'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_image',
            field=models.ImageField(blank=True, upload_to='video_images', verbose_name='Image of music'),
        ),
    ]
